"""empty message

Revision ID: 586360252138
Revises: 917ed57621d6
Create Date: 2021-10-30 21:05:07.734574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586360252138'
down_revision = '917ed57621d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
